# Generated by Django 3.2.6 on 2021-09-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210904_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_64',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
