# Generated by Django 3.2.6 on 2021-09-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_alter_usuario_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telfijo',
        ),
    ]
