# Generated by Django 3.2.6 on 2021-09-16 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0005_auto_20210915_2236'),
        ('loginapp', '0005_remove_usuario_telfijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.ciudad'),
        ),
    ]
