# Generated by Django 3.2.6 on 2021-09-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
