# Generated by Django 3.2.6 on 2021-09-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_usuario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_64',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
