# Generated by Django 3.2.6 on 2021-09-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de cuenta',
                'verbose_name_plural': 'tipos de cuentas',
                'db_table': 'tipo_cuenta',
            },
        ),
        migrations.CreateModel(
            name='tipo_empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de empleado',
                'verbose_name_plural': 'tipos de empleados',
                'db_table': 'tipo_empleado',
            },
        ),
        migrations.CreateModel(
            name='tipo_identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de identificacion',
                'verbose_name_plural': 'tipos de identificacion',
                'db_table': 'tipo_identificacion',
            },
        ),
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de usuario',
                'verbose_name_plural': 'tipos de usuarios',
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.tipo_cuenta')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'db_table': 'cuenta',
            },
        ),
    ]
