# Generated by Django 3.2.6 on 2021-09-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0002_negocio_producto_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
