# Generated by Django 3.2.6 on 2021-09-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_auto_20210912_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='negocio',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='negocio',
            name='telefono1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='telefono2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
