# Generated by Django 3.2.6 on 2021-09-16 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0004_auto_20210912_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'categoria de producto',
                'verbose_name_plural': 'categorias de producto',
                'db_table': 'categoria_productos',
            },
        ),
        migrations.CreateModel(
            name='categoria_servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'categoria de servicio',
                'verbose_name_plural': 'categorias de servicio',
                'db_table': 'categoria_servicios',
            },
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.departamento')),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(to='systemapp.categoria_productos'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categorias',
            field=models.ManyToManyField(to='systemapp.categoria_servicios'),
        ),
    ]
