# Generated by Django 3.2.6 on 2021-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0008_auto_20210917_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
