# Generated by Django 3.2.6 on 2021-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0009_alter_negocio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='imagen_64',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_64',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_64',
            field=models.TextField(null=True),
        ),
    ]
