# Generated by Django 3.2.6 on 2021-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0010_auto_20210917_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'categoria de negocio',
                'verbose_name_plural': 'categorias de servicio',
                'db_table': 'categoria_negocio',
            },
        ),
        migrations.CreateModel(
            name='CIIU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciiu', models.CharField(max_length=7, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'categoria de producto',
                'verbose_name_plural': 'categorias de producto',
                'db_table': 'CIIU',
            },
        ),
    ]
