# Generated by Django 3.2.6 on 2021-09-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0011_categoria_negocio_ciiu'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_productos',
            name='cat_negocio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.categoria_negocio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria_servicios',
            name='cat_negocio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.categoria_negocio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negocio',
            name='categorias',
            field=models.ManyToManyField(to='systemapp.categoria_negocio'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.ciudad'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='negocio_ciiu',
            field=models.ManyToManyField(to='systemapp.CIIU'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.departamento'),
        ),
    ]
