# Generated by Django 3.2.6 on 2021-09-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0012_auto_20210918_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(db_column='departamento_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.departamento'),
        ),
    ]
