# Generated by Django 3.2.6 on 2021-09-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0013_alter_ciudad_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='categorias',
            field=models.ManyToManyField(null=True, to='systemapp.categoria_negocio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(null=True, to='systemapp.categoria_productos'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categorias',
            field=models.ManyToManyField(null=True, to='systemapp.categoria_servicios'),
        ),
    ]
