# Generated by Django 3.2.6 on 2021-09-18 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemapp', '0015_auto_20210918_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'metodo de pago',
                'verbose_name_plural': 'metodos de pago',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.AlterField(
            model_name='negocio',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='systemapp.categoria_negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='negocio_ciiu',
            field=models.ManyToManyField(blank=True, to='systemapp.CIIU'),
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_recibido', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_devuelto', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.metodo_pago')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.negocio')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='carrito_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('facturas', models.ManyToManyField(to='systemapp.factura')),
                ('productos', models.ManyToManyField(to='systemapp.producto')),
                ('servicios', models.ManyToManyField(to='systemapp.servicio')),
            ],
            options={
                'verbose_name': 'carrito de compra',
                'verbose_name_plural': 'carritos de compra',
                'db_table': 'carrito_compra',
            },
        ),
    ]
