# Generated by Django 3.2.6 on 2021-09-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0018_auto_20210918_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_compra',
            name='facturas',
            field=models.ManyToManyField(blank=True, to='systemapp.factura'),
        ),
        migrations.AlterField(
            model_name='carrito_compra',
            name='productos',
            field=models.ManyToManyField(blank=True, to='systemapp.producto'),
        ),
        migrations.AlterField(
            model_name='carrito_compra',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='systemapp.servicio'),
        ),
    ]
