# Generated by Django 3.2.6 on 2021-09-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0020_auto_20210919_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
