# Generated by Django 3.2.6 on 2021-09-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0021_negocio_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, default=5, max_digits=2, null=True),
        ),
    ]
