# Generated by Django 3.2.6 on 2021-10-10 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0023_auto_20210919_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito_compra',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='carrito_compra',
            name='servicios',
        ),
        migrations.AlterField(
            model_name='producto',
            name='negocio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='systemapp.negocio'),
        ),
        migrations.CreateModel(
            name='carrito_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('carrito_compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.carrito_compra')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.servicio')),
            ],
            options={
                'db_table': 'carrito_servicio',
            },
        ),
        migrations.CreateModel(
            name='carrito_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('carrito_compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.carrito_compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.producto')),
            ],
            options={
                'db_table': 'carrito_producto',
            },
        ),
        migrations.AddField(
            model_name='carrito_compra',
            name='producto',
            field=models.ManyToManyField(through='systemapp.carrito_producto', to='systemapp.producto'),
        ),
        migrations.AddField(
            model_name='carrito_compra',
            name='servicio',
            field=models.ManyToManyField(through='systemapp.carrito_servicio', to='systemapp.servicio'),
        ),
    ]
