# Generated by Django 3.2.6 on 2021-10-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0024_auto_20211009_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_compra',
            name='servicio',
            field=models.ManyToManyField(blank=True, through='systemapp.carrito_servicio', to='systemapp.servicio'),
        ),
        migrations.AlterField(
            model_name='carrito_producto',
            name='carrito_compra',
            field=models.ForeignKey(db_column='carrito_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.carrito_compra'),
        ),
        migrations.AlterField(
            model_name='carrito_producto',
            name='producto',
            field=models.ForeignKey(db_column='producto', on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.producto'),
        ),
    ]
