# Generated by Django 3.2.6 on 2021-10-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0025_auto_20211010_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='systemapp.carrito_compra'),
        ),
    ]
