# Generated by Django 3.2.6 on 2021-10-20 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemapp', '0026_factura_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'factura_servicio',
            },
        ),
        migrations.RenameModel(
            old_name='carrito_servicio',
            new_name='factura_producto',
        ),
        migrations.RemoveField(
            model_name='carrito_producto',
            name='carrito_compra',
        ),
        migrations.RemoveField(
            model_name='carrito_producto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='factura_producto',
            name='carrito_compra',
        ),
        migrations.RemoveField(
            model_name='factura_producto',
            name='servicio',
        ),
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(through='systemapp.factura_producto', to='systemapp.producto'),
        ),
        migrations.AddField(
            model_name='factura_producto',
            name='factura',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.factura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura_producto',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='factura_producto',
            table='factura_producto',
        ),
        migrations.DeleteModel(
            name='carrito_compra',
        ),
        migrations.DeleteModel(
            name='carrito_producto',
        ),
        migrations.AddField(
            model_name='factura_servicio',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.factura'),
        ),
        migrations.AddField(
            model_name='factura_servicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.servicio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='servicios',
            field=models.ManyToManyField(blank=True, through='systemapp.factura_servicio', to='systemapp.servicio'),
        ),
    ]
