# Generated by Django 3.2.6 on 2021-10-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0027_auto_20211019_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='negocio', to='systemapp.negocio'),
        ),
    ]
