# Generated by Django 3.2.6 on 2021-10-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0028_alter_factura_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='imagen_64',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_64',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen_64',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
