# Generated by Django 3.2.6 on 2021-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0030_alter_producto_imagen_64'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('AT', 'Atendido'), ('PE', 'Pendiente'), ('RE', 'Rechazado'), ('CA', 'Cancelado')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
