# Generated by Django 3.2.6 on 2021-10-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0036_alter_factura_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_factura',
            },
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.estado_factura'),
        ),
    ]
