# Generated by Django 3.2.6 on 2021-11-06 04:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0038_alter_factura_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_pedido',
            },
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.estado_pedido')),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.factura')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
