# Generated by Django 3.2.6 on 2021-11-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0039_estado_pedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cel_contacto',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
