# Generated by Django 3.2.6 on 2021-11-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0040_auto_20211106_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cel_contacto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tel_contacto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
