# Generated by Django 3.2.6 on 2021-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0041_auto_20211106_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='valor_domicilio',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='valor_domicilio',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000, max_digits=7, null=True),
        ),
    ]
