# Generated by Django 3.2.6 on 2021-11-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0042_auto_20211107_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_transporte',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transporte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.tipo_transporte'),
        ),
    ]
