# Generated by Django 3.2.6 on 2021-11-22 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0043_auto_20211107_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.metodo_pago'),
        ),
    ]
