# Generated by Django 3.2.6 on 2021-11-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0044_alter_factura_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.estado_factura'),
        ),
    ]
